### ISSUE TITLE
z-Anordnung

### ISSUE THREAD

**Issue by caroschwerdt** [achim1/ctplot#12]
Wofür gut? Hab <0, >0 und keine Eingabe ausprobiert, es hat sich im Bild nichts geändert.
![plot809631286136371145](https://cloud.githubusercontent.com/assets/13692433/11034267/9d9b9330-86ea-11e5-875b-31a1b134735f.png)
![plot-5462125315656561845](https://cloud.githubusercontent.com/assets/13692433/11034266/9d9b91fa-86ea-11e5-8d98-b8c5bd1dc3a5.png)
![plot-8549187582686941294](https://cloud.githubusercontent.com/assets/13692433/11034268/9d9e832e-86ea-11e5-9d77-36a842d90d2e.png)

**Comment by martinohmann** [comment]
Die z-Anordnung ist nur relevant, wenn man zwei oder mehr Datensätze plottet. Sie bestimmt die Reihenfolge, in der die Graphen geplottet werden. Kann eine beliebige natürliche Zahl sein. Die Graphen werden nach deren z-Anordnung geplottet, beginnend von der niedrigsten. D.h. also, dass der Graph mit der höchsten z-Anordnung am Weitesten "vorn" ist.

Ich denke dass hier lediglich die Dokumentation überarbeitet werden muss. Das Feature an sich ist sinnvoll und funktioniert auch so wie es soll. 

Alternativ kann man das Feature klarer machen, wenn man das Eingabefeld in ein Dropdown Menü mit den Auswahlmöglichkeiten "1. Ebene" bis "4. Ebene" umwandelt. Dann ist das vielleicht klarer, was dort passiert. Es ist auch unproblematisch, wenn man bei mehrere Datenreihen den gleichen Wert auswählt. Dann entscheidet die Plotbibliothek was weiter vorn ist.

**Comment by caroschwerdt** [comment]
Also ist das eine Art "Plazierung" / "Ebene nach vorn/hinten"? 

Dropdown Menü finde ich gut!
Vielleicht findest du noch einen anderen Namen für "z-Anordnung"?

**Comment by martinohmann** [comment]
Ja genau, das ist die Platzierung, Graphen "weiter hinten" werden eben von den Graphen "weiter vorn" überlappt. "z-Anordnung" wurde auch schon beim Neusetzen der Formularfelder in "Anordnung" umbenannt. Ich werde das dann mit einem Dropdown lösen und den Hilfetext entsprechend einleuchtender gestalten.
