### ISSUE TITLE
Korrektur der Variablen

### ISSUE THREAD

**Issue by caroschwerdt** [achim1/ctplot#21]
Unter Auswahl der Variablen nochmal zu jeder Variable Möglichkeit geben um benutzerdefinierte Sachen einzugeben.

**Comment by martinohmann** [comment]
Bitte nochmal spezifizieren. Es handelt sich vermutlich um einen Multiplikator, den man auf die Werte der x- bzw. y-Achse anwendet. Ist dies einfach ein int/float, oder eine Formel? Wie würde eine übliche Formel aussehen?

**Comment by caroschwerdt** [comment]
Ein Beispiel ist: Man muss die Muonen-Rate R von Luftdruckschwankungen p korrigieren.
Auf der y-Achse möchte man dann die korrigierte Rate R_k in Abhängigkeit vom jeweiligen Luftdruck p, normiert auf einen festgelegten Luftdruck p_k, abtragen.
Beta ist der Korrekturfaktor (fester Wert), p und R (mu_rate) sind im Datensatz enthalten.
Formel sieht so aus: 
![formel](https://cloud.githubusercontent.com/assets/13692433/11807508/7fe32460-a31a-11e5-8d9c-d0c9eb16ce0e.jpg)

**Comment by martinohmann** [comment]
Das feature ist eingebaut und kann getestet werden.

**Comment by martinohmann** [comment]
Es wäre noch zu überlegen, ob die verwendeten Korrekturfunktionen mit im Plot auftauchen sollen. Wenn ja, in welcher Form und wo?

**Comment by caroschwerdt** [comment]
Ich denke, es ist ok, so wie es jetzt ist (also Korrekturterm steht an Achse)
![plot-223980374169713446](https://cloud.githubusercontent.com/assets/13692433/12752674/f068440c-c9c3-11e5-83d2-0185542e613b.png)
