### ISSUE TITLE
Startwert und Ebndwert voneinander abhängig

### ISSUE THREAD

**Issue by caroschwerdt** [achim1/ctplot#23]
Wenn man bei Startwert oder Endwert einen Eintrag macht, muss man auch beim anderen einen Eintrag vornehmen, sonst wird ein Fehler ausgespuckt. -> wollen wir nicht. Wenn ein Wert nicht eingetragen wird, dann dafür default nehmen.

**Comment by martinohmann** [comment]
fixed via commit 5d2ff91db88bcc9f84d2b4b494f23448650d17b8
