### ISSUE TITLE
Optional

### ISSUE THREAD

**Issue by caroschwerdt** [achim1/ctplot#3]
In Felder in denen nichts eingetragen werden muss, soll in blass grau stehen: "optional"

**Comment by martinohmann** [comment]
Hier müssen wir nochmal genauer schauen, welche Felder als optional deklariert werden müssen. In den Styleguides die mir vorliegen war das meiner Meinung nach nur teilweise deklariert. Ich habe in commit f7be729e20792bc2ea4b5b7ff49da24ca5643837 aber zumindest schonmal alles als optional deklariert, was m.M.n. auch optional sein soll.

**Comment by caroschwerdt** [comment]
Okay, nach überlegungen haben wir uns dazu entschlossen nur die z-Variable als optional anzuzeigen.
