### ISSUE TITLE
x-Achse Day/Hour/Month/Jahr abtragen

### ISSUE THREAD

**Issue by caroschwerdt** [achim1/ctplot#31]
Auf x-Achse nicht alle Tage eines Jahres in einem Bin zusammenfassen, sondern getrennt betrachten (d.h. 1.Februar ist anderer Tag als 1. April). Also z.B. 365 Tage auf der x-Achse darstellen.

**Comment by martinohmann** [comment]
Duplicate of issue #14, closed

**Comment by martinohmann** [comment]
Duplicate of issue #14, closed
