### ISSUE TITLE
Fit-Funktionen besser kennzeichnen?

### ISSUE THREAD

**Issue by martinohmann** [achim1/ctplot#36]
![2015-12-10-024511_897x629_scrot](https://cloud.githubusercontent.com/assets/1335045/11704446/29a66d40-9ee8-11e5-904a-8ffccc38f2f6.png)
In den Ecken sieht man die zu den drei Fit-Funktionen zugehörigen Werte. Ich habe jeweils die gleiche Fit-Funktion gewählt.

Welche Statistik-Box gehört jetzt zu welcher Fit-Funktion? In meinem Beispiel kann man das noch irgendwie herrausfinden, wenn man genauer hinschaut.

Vielleicht die Linienfarbe auch in der jeweiligen Statistikbox anzeigen? Vorschläge?

**Comment by caroschwerdt** [comment]
Ja, das ist eine gute Idee. Oder: Die die Schriftfarbe der Fit-Funktion, die in der Statistikbox an erster Stelle steht, in der entsprechenden Farbe darstellen? Ist nur eine Idde, du kannst entscheiden, wie es besser aussieht!

**Comment by martinohmann** [comment]
Ich werde einfach mal ausprobieren was am besten aussieht.
