### ISSUE TITLE
Backwards Compatibility

### ISSUE THREAD

**Issue by martinohmann** [achim1/ctplot#37]
Muss ctplot abwärtkompatibel sein? D.h.: gibt es momentan Nutzer, die ctplot aktiv nutzen, vorallem die Funktion "Gespeicherte Diagramme"?

Ich würde sonst soetwas wie das hier dauerhaft implementieren:
https://github.com/achim1/ctplot/blob/master/ctplot/wsgi.py#L152-L160

Es geht hier um die 'plotcount' variable. Ich habe die im frontend eingeführt um zuverlässig die anzahl der datenreihen an das backend zu übergeben. Ich würde im backend keine plot-requests mehr abarbeiten, die diese variable nicht mitsenden.

Das würde jedoch die settings der bestehenden Nutzer ungültig machen.

Deshalb die Frage: gibt es bestehende Nutzer?

**Comment by caroschwerdt** [comment]
Das kannst du machen. Es gibt eventuell ein oder zwei Nutzer, aber mit der Erneuerung des Webinterfaces macht es Sinn, auch wieder die Plots neu zu generieren.
