### ISSUE TITLE
x ändern zum schließen einer Datenreihe

### ISSUE THREAD

**Issue by caroschwerdt** [achim1/ctplot#38]
Kannst du bitte ein anderes x für das schließen einer Datenreihe aussuchen?

**Comment by martinohmann** [comment]
Wie ist das gemeint? Andere Farbe, oder andere Schriftart? Das ist momentan ein Icon aus font-awesome (https://fortawesome.github.io/Font-Awesome/icons/). 

Man könnte das Ganze natürlich invertieren und z.B. ein weißes Kreuz in einen roten Kreis tun. Habe das hier mal als Beispiel getan auch mit andersfarbigen Varianten: https://jsfiddle.net/4nntfsda/1/.

**Comment by caroschwerdt** [comment]
Mir ist das bisherige x zu fett. Ich würde was eckiges gut finden, weil wir die anderen Icon-Boxen auch eckig haben. Und dit rot könnte nen ticken dunkler sein, nicht ganz so aggressiv. 
So in der Art: 
![capture](https://cloud.githubusercontent.com/assets/13692433/12580204/e8abe37c-c42d-11e5-8401-bb4e15540c69.PNG)?

**Comment by martinohmann** [comment]
Änderungsbeispiel kann in der Entwicklungsumgebung angesehen werden.

**Comment by caroschwerdt** [comment]
Kannst du es bitte noch etwas kleiner machen? In etwa so groß, wie das D bei Datenauswahl?

**Comment by martinohmann** [comment]
besser?

**Comment by caroschwerdt** [comment]
Ja! Perfekt :-)
