### ISSUE TITLE
Darstellungen im Diagramm

### ISSUE THREAD

**Issue by caroschwerdt** [achim1/ctplot#39]
![capture](https://cloud.githubusercontent.com/assets/13692433/12443222/b008027a-bf56-11e5-8707-1e8ce1389ca2.PNG)
- Kann per default für zwei Datenreihen blau und rot genommen werden?
- Warum doppelter Punkt in der Legende?

**Comment by martinohmann** [comment]
Anzahl der Symbol pro Legendeneintrag auf 1 gesetzt. Closed.
