### ISSUE TITLE
Diagramm speichern

### ISSUE THREAD

**Issue by caroschwerdt** [achim1/ctplot#4]
Wenn man auf die Diskette für "Diagramm speichern" klickt, verschwindet die Diskette und es wird nichts gespeichert bzw. geht kein neues Feld zur Angabe des Download-Ortes auf.

**Comment by martinohmann** [comment]
Ich glaube hier gibt es eher ein Verständnisproblem. Ein Klick auf die Diskette bewirkt, dass das Diagramm unten auf der Seite den gespeicherten Diagrammen der Session hinzugefügt wird. Speichern des Diagramms auf der Festplatte geht über die PDF/SVG-Downloadfunktion.

Vielleicht sollte mal hier die Rückmeldung verbessern, z.B. dass nach dem Klicken auf die Diskette zu den gespeicherten Diagrammen gescrollt wird und evtl. eine Meldung ausgegeben wird.

Oder man ersetzt die Diskette durch einen Textlink, der etwas einleuchtender ist, z.B.: "zu gespeicherten Diagrammen hinzufügen"
