### ISSUE TITLE
Darstellung der Oberfläche

### ISSUE THREAD

**Issue by caroschwerdt** [achim1/ctplot#41]
![capture](https://cloud.githubusercontent.com/assets/13692433/12506892/70786030-c0f2-11e5-9afb-4e0d46bd0302.PNG)
Das gefällt uns noch nicht so recht.

Kannst du zwei Vorschläge machen?
1)
Einstellung für das Diagramm (als Ersatz für Diagramm-Einstellungen)
Einstellungsmodi (Als Überschrift der Box)
Auswahlmöglichkeit
2)
Einstellung für das Diagramm (als Ersatz für Diagramm-Einstellungen)
Einstellungsmodi (Als Überschrift der Box)
Auswahlmöglichkeit als Überschrift löschen

**Comment by martinohmann** [comment]
Etwa so?

Nummer 1:
![2016-01-26-134233_978x124_scrot](https://cloud.githubusercontent.com/assets/1335045/12580812/d9450580-c432-11e5-90d6-5f2d270f97c7.png)

Nummer 2:
![2016-01-26-134314_971x111_scrot](https://cloud.githubusercontent.com/assets/1335045/12580813/d949de52-c432-11e5-8e2a-04b492e14a86.png)

Ich würde in der Überschrift auch "Einstellungen" anstatt "Einstellung" verwenden (wie schon in den Screenshots angedeutet).

**Comment by caroschwerdt** [comment]
Nummer 2 passt jut. Und genau: "Einstellungen" ist besser.
