### ISSUE TITLE
3D Plot nicht möglich

### ISSUE THREAD

**Issue by csteppa** [achim1/ctplot#42]
Sobald eine z-Variabe ausgewählt ist, erscheint beim Versuch ein Diagramm zu erstellen die Fehlermeldung:

"Unbekannter Fehler: Do not know how to convert none to dashes".

Dieser Fehler scheint unabhängig von der ausgewählten Darstellungsform und der Kombination der Variablen zu sein.

**Comment by martinohmann** [comment]
Kannst du mir mal konkrete Eingaben nennen, mit denen der Fehler auftritt? Ich bekomme das Verhalten hier leider nicht reproduzieren.

**Comment by csteppa** [comment]
Mit folgenden Einstellungen erhalte ich beispielsweise die Fehlermeldung

1)
Erweitert
Polarstern
2013_PS-nm-my
xy-Diagramm
time
lat
p

2)
Erweitert
Polarstern
2013_PS-nm-my
Karte
lon
lat
p

3)
Erweitert
Polarstern
2013_PS-nm-my
Karte
lon
lat
mu_rate

**Comment by martinohmann** [comment]
Der 3D plot macht Probleme, wenn der Linientyp 'Keine Linie' ist. Habe das abgefangen.
