### ISSUE TITLE
Pillow-Abhängigkeit

### ISSUE THREAD

**Issue by caroschwerdt** [achim1/ctplot#43]
In Zusammenhang mit der Aufstellung des neuen Servers, ist aufgefallen, dass das einzige externe Paket was gebraucht wird, Pillow ist.

Nun folgende Frage an dich Martin: braucht Cosmic@Web Pillow? Oder kann es ggf. ersetzt werden?

**Comment by martinohmann** [comment]
Du meintest wohl das veraltete PIL. Pillow ist eine neuere Variante davon, die aktiv weiterentwickelt wird. PIL bzw. Pillow wird zum Zeichnen der Karte benötigt. 

Ich habe PIL als dependency entfernt und durch Pillow ersetzt.

**Comment by caroschwerdt** [comment]
Ist das Problem jetzt wirklich behoben? 

Beim neuen Server sollen nur Pakete genutzt werden, die in SL7 enthalten sind. Ist Pillow da dabei, weißt du das?

**Comment by martinohmann** [comment]
Es geht hier wohl eher darum, ob das Paket aus der offiziellen Quelle für Python-Pakete bezogen werden kann (Pythons Paketmanager python-pip) oder direkt als RPM Paket aus den SL7 Paketquellen beziehbar ist. Pillow ist über python-pip sowie den SL7 Paketmanager verfügbar, PIL nicht.

**Comment by caroschwerdt** [comment]
Ja, genau. Super! Damit ist das auch erledigt :-)
