### ISSUE TITLE
Warum geht das nicht? Fitten?

### ISSUE THREAD

**Issue by caroschwerdt** [achim1/ctplot#48]
![1](https://cloud.githubusercontent.com/assets/13692433/12752809/865e0c44-c9c4-11e5-8047-9ed450b7060c.PNG)
![2e](https://cloud.githubusercontent.com/assets/13692433/12752810/8663e7d6-c9c4-11e5-98eb-52a3b9adaa7a.PNG)
![3](https://cloud.githubusercontent.com/assets/13692433/12752812/866d25d0-c9c4-11e5-99b9-2b8e3ef1704b.PNG)
![4](https://cloud.githubusercontent.com/assets/13692433/12752811/866a146c-c9c4-11e5-960d-15dd79e75de7.PNG)
Ich habe die Muonenrate logarithmisch über dem Luftdruck abgetragen und wollte nun eine gerade hineinfitten.

**Comment by martinohmann** [comment]
Du musst natürlich die Startparameter für p[0] und p[1] setzen, sonst geht das nicht.

**Comment by caroschwerdt** [comment]
:~) klar!
