### ISSUE TITLE
Eingaben verschwinden nach Speicherung Diagramm

### ISSUE THREAD

**Issue by caroschwerdt** [achim1/ctplot#5]
Nachdem man auf "png" geklickt hat, um ein Bild zu speichern, und dann im Browser auf den Zurückpfeil klickt, sind die Eingaben unter Raten-Berechnung, Variablen etc. weg. Nur das Experiment, der Datensatz und die Dartstellungsform bleibt erhalten.

**Comment by martinohmann** [comment]
Wird nicht so einfach. Kann aber umgangen werden, indem man die Download-Links anweist, das Diagramm in einem neuen Tab zu öffnen. Dann bleibt der aktuelle Zustand des Formulars erhalten.

**Comment by martinohmann** [comment]
fixed by commit c7aceff29f85f5726f736e29d84fef5e214c809f
