### ISSUE TITLE
Diagramm-Option: Marker und Linie

### ISSUE THREAD

**Issue by caroschwerdt** [achim1/ctplot#6]
Wenn "kein Marker" ausgewählt ist, wird trotz "durchgezogener Lienie" keine Linie gezeichnet. 
Wollen wir das so?

**Comment by martinohmann** [comment]
Im Endeffekt gibt es ohne Marker ja auch nichts, was man mit einer Linie verbinden könnte, von daher macht das so schon Sinn.

**Comment by caroschwerdt** [comment]
ok, dmait hat sich der Issues erledigt!
