### ISSUE TITLE
Schreibweise deutsch/englisch

### ISSUE THREAD

**Issue by caroschwerdt** [achim1/ctplot#7]
Cosmic@Web ist auf deutsch geschrieben, Eingaben müssen z.T. in englisch erfolgen -> das sollten wir abschaffen. Beispiel: Dezimalzahlen müssen mit Punkt statt mit Komma eingegeben werden, Bezeichnung der Daten. Es sollte alles mit deutscher Schreibweise beschrieben/eingegeben werden.

**Comment by caroschwerdt** [comment]
z.b bei Bedingungen: wenn Komma verwendet wird, wird in Englisch umgewandelt
oder
bei Statistikbox wird in deutsch übersetzt
aber 
bei Bezeichnung (weil Textangabe) nicht

**Comment by martinohmann** [comment]
An einigen Stellen werden kommaseparierte Eingaben erwartet. Hier würde es Konflikte mit der deutschen Dezimalnotation geben. Deshalb als wontfix markiert. Dies gilt natürlich nicht für die Übersetzungen.

**Comment by martinohmann** [comment]
Kann eigentlich geschlossen werden, da deutsche Bezeichnungen in den Statistikboxen entweder entweder viel zu lang sind, oder in kryptischen Abkürzungen enden würden.

**Comment by caroschwerdt** [comment]
Ja, kann geschlossen werden.
