### ISSUE TITLE
Fehlermeldung/Errorhandling

### ISSUE THREAD

**Issue by caroschwerdt** [achim1/ctplot#8]
Wenn es der Software nicht gelingt ein Diagramm zu erstellen, sollte sie dem Benutzer zurück geben, an welcher Stelle der Fehler entsteht.

**Comment by martinohmann** [comment]
erledigt

**Comment by csteppa** [comment]
Falls Diagramm erstellt werden soll ohne Experiment und Datensatz zuvor ausgewählt zu haben, erhält der Nutzer die Fehlermeldung " Unbekannter Fehler: 's0' ".

**Comment by martinohmann** [comment]
Fehler behoben.

**Comment by csteppa** [comment]
![bildschirmfoto 2016-01-29 um 11 43 44](https://cloud.githubusercontent.com/assets/16834003/12673571/d50035ba-c67d-11e5-9f10-83fca7cf2b0a.png)

"Unbekannter Fehler" falls Komma statt Punkt zur Dezimaltrennung verwendet wird (siehe Bedingung)

**Comment by martinohmann** [comment]
Komma als Dezimaltrenner ist nicht möglich, da in den Feldern, wo Expressions eingetragen werden können (x/y/z-Korrketur, Bedingung, Fitfunktion) auch numpy-Funktionen benutzt werden können, welche mehrere Parameter erwarten und das Komma daher zur Parametertrenner benutzt wird.

Der Validator wirft jetzt eine aussagekräftigere Fehlermeldung, falls man versucht Kommata als Dezimaltrenner innerhalb der Expressions zu benutzen.
