### ISSUE TITLE
Karte 

### ISSUE THREAD

**Issue by caroschwerdt** [achim1/ctplot#9]
Funktioniert irgendwie nicht, oder ich kann sie nicht bedienen? -> nochmal anschauen.

**Comment by caroschwerdt** [comment]
Funktioniert nur, wenn man Latitude und Londitute angibt

**Comment by caroschwerdt** [comment]
Dokumentation anpassen! Und Fehlermeldung aussagekräftig.

**Comment by martinohmann** [comment]
User erhält nun Meldung im Frontend, dass er doch bitte Latitude bzw. Longitude als x/y-Variablen verwenden soll.
